### PR TITLE
Set the encryption key to a random value if it is not defined

### PR DESCRIPTION
**Pull request by Godwottery**
This should fix the issue in https://github.com/PowerDNS/dnsdist-ansible/issues/2
I encountered a similar problem when trying to install a new copy of dnsdist. 

I have not found a good solution how to collect the generated secret, but this might not be necessary for the cases when random one is generated.

### CODE REVIEW

**Comment by Godwottery** [comment]
This method fails idempotency checks in the tests. In my view this is acceptable behaviour, as it will only be run when there is nothing set, and then one would expect a new value every time.

**Comment by atosatto** [comment]
Hi @Godwottery sorry for taking so long to reply to your PR.

First of all, thanks for this! It is indeed a very useful feature.
I have however one questions and one concern on the propose implementation:

1. what's the ` Register key to file` task used for?
2. there are scenarios in which the user might use the `dnsdist_config` variable to inject the key. In that case, setting `dnsdist_setkey: ""` is a way to prevent the key to be added anyway to the template.

If you are still interested in contributing this feature, I would propose you the following strategy:

1. add a new variable named  `dnsdist_generatekey` set by default to `dnsdist_setkey == ''`, so that if no key is defined, we generate it by default
2. if `dnsdist_generatekey` is true, and the `dnsdist.conf` file has no `setKey` entry, we generate it and set the value of the `dnsdist_setkey` so that the `Add the dnsdist configuration` will add it to the template

The pseudo-code for 2 can be

```yaml
- block:

  - name: Check if the key is already present in the DNSdist configuration file 
     shell: fgrep setKey /etc/dnsdist/dnsdist.conf
     register: dnsdist_grepkey_cmd

  - block:

    - name: Generate encryption key
      shell: head -c 32 /dev/urandom | base64
      register: dnsdist_generatekey_cmd

    - name: Set the encryption key
      set_fact:
        dnsdist_setkey: "{{ dnsdist_generatekey_cmd.stdout }}"

    when: "dnsdist_grepkey_cmd.rc > 0 or dnsdist_grepkey_cmd.stdout | length == 0"  # if the file does not exist or setKey is not in the file

  when: dnsdist_generatekey
```

**Comment by Godwottery** [comment]
> 1. what's the ` Register key to file` task used for?
No idea. I probably had a thought behind it, but I can not see the use now. 

> 2. there are scenarios in which the user might use the `dnsdist_config` variable to inject the key. In that case, setting `dnsdist_setkey: ""` is a way to prevent the key to be added anyway to the template.
Sounds like a good idea.

**Comment by Godwottery** [comment]
I refactored it a little bit. 
If dnsdist_setkey is not defined it will not create a key. 
If dnsdist_setkey is defined as empty string, it will check if there already is a key, otherwise generate one.
If dnsdist_setkey is defined as a non-empty string, it will be set.

**Comment by Godwottery** [comment]
Something happened during the refactoring, so there seems to be some "stuff" in there that is from another commit.

**Comment by atosatto** [comment]
Looks good to me! Great work, thanks!

**Pull request merged**
