### PR TITLE
Vault-safe test for dnsdist_setkey, fixes #30

### LINKED ISSUE #30: setup fails with a vaulted setKey() value
As discussed on IRC:

If you try to run the playbook with the dnsdist_setkey value as a vaulted string, the setup fails with the following error message:

`fatal: [agni]: FAILED! => {"msg": "The conditional check 'dnsdist_generatekey' failed. The error was: Unexpected templating type error occurred on ({{ (dnsdist_setkey is defined)|bool and (dnsdist_setkey|length == 0 )|bool }}): object of type 'AnsibleVaultEncryptedUnicode' has no len()\n\nThe error appears to be in '/home/shadur/.ansible/roles/PowerDNS.dnsdist/tasks/main.yml': line 20, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: Check if the key is already present in the DNSdist configuration file\n      ^ here\n"}`

What's actually going wrong is in the `defaults/main.yml` file on line 72:

```
# dnsdist's control socket encryption key.
# See https://dnsdist.org/reference/config.html#setKey for more information.
dnsdist_generatekey: "{{ (dnsdist_setkey is defined)|bool and (dnsdist_setkey|length == 0 )|bool }}"
```

This fails because dnsdist_setkey is an `AnsibleVaultEncryptedUnicode` object, while the `| length` function attempts to call `str.len()`.

### PR DESCRIPTION
**Pull request by lpmhouben**
This should fix the issue.

### CODE REVIEW

**Comment by Habbie** [comment]
Did you also test this without vault?

**Comment by lpmhouben** [comment]
No, but I'm still poking at this one so give me a minute and I'll retest.

**Comment by lpmhouben** [comment]
Works with vaulted or plaintext.

**Comment by lpmhouben** [comment]
... I'm not sure what's causing those breaks but I don't think it's actually related to what I changed.

**Pull request merged**
